### ISSUE TITLE
autodiscovery centos kms server

### ISSUE THREAD

**Issue by kine0808** [ThunderEX/py-kms#14]
HI,Guys. I install the py-kms on my centos 7 server. I can  use CMD to active my windows and office,but can not auto active.
I added _vlmcs on my DNSer  ,but it still not work.
Anyone  has the problem like this? How can fix it?
thinks

**Comment by ThunderEX** [comment]
Hi kine,

This is a problem of auto discovery instead of this kms simulator. So I would suggest you ask the question in [forum](https://forums.mydigitallife.net/forums/kms-tools.51/) as it's more possible to get help there.

As for this project, I'll try to add some guide to auto discovery later.
