### ISSUE TITLE
Run with Python 2.6 on CentOS6 has an "param error“

### ISSUE THREAD

**Issue by sanjusss** [ThunderEX/py-kms#15]
When a win10 PC  connected server (Python 2.6 on CentOS6), it has an "param error“. I have not recorded the details.
I upgraded Python to 2.7 on same server,  then no error occurred.

**Comment by ThunderEX** [comment]
I pushed a commit a075ff3 to fix issues with Python 2.6 on Windows. You may want to try run on CentOS 6 again😁.
