### ISSUE TITLE
KMS GVLK for LTSC and LTSC N are available

### ISSUE THREAD

**Issue by Nh3xus** [ThunderEX/py-kms#19]
Hello,

MS has released the GVLK for LTSC 2019 and LTSC N 2019 on their website.

Here's the list :

Windows 10 entreprise LTSC 2019 | M7XTQ-FN8P6-TTKYV-9D4CC-J462D
skuid : 32d2fab3-e4a8-42c2-923b-4bf4fd13e6ee
Windows 10 entreprise N LTSC 2019 | 2NFX-8DJQP-P6BBQ-THF9C-7CG2H
skuid : 7103a333-b8c8-49cc-93ce-d37c09687f92

Cheers.

EDIT : I updated the post with the relevant skuid

**Comment by martinsstuff** [comment]
py-kms can activate these as it doesn't rely on the skuID's like the old py-kms, right? (The non-python version's latest update v1111 can)

**Comment by Nh3xus** [comment]
How are skuid computed ?

I can't find the skuid for these new versions.

**Comment by ThunderEX** [comment]
Hi both,
py-kms should work with latest KmsDataBase.xml from License Manager from Hotbird64. But actually there are something (such as app id for epid generation) not using KmsDataBase.xml. So I will correct these in a few days.
If you have any time, you can also test py-kms with latest KmsDataBase.xml and report any problem with windows 1809.

**Comment by ThunderEX** [comment]
Hi both,
I've updated 138e53e4d4f8a515bbfad6f7eb670f1c991f16a2, which could reply correct epid key and also update KmsDataBase.xml.
You can freely test it. If everything is fine, I'll close this issue in a few days.

**Comment by Nh3xus** [comment]
Yup, your commit works.

LTSC 2019 activates without any error :)
