### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dimqua** [ThunderEX/py-kms#25]
Please consider to create at least one stable release.

**Comment by ThunderEX** [comment]
Hi @dimqua , why do you think we need a release? what's the benefit of release instead of using latest version directly?

**Comment by dimqua** [comment]
For users:
* You can easily figure out which version of the software you already have (latest or not).
It's easy to decide to update to the latest version or not (yet), thanks to [semantic versioning](https://semver.org).
* You can check the status of each release, and (for example) update to major releases only.
* You can access to more detailed changelogs (commit history is not enough in some cases).

As a developer, you can make ground-breaking changes and provide stable releases at the same time (although you can use separate branches for that).

---
But I'm not compeltly sure that any of these reasons are applicable to such a small project like this one. So if you think they are not, feel free to close this issue.

**Comment by ThunderEX** [comment]
Hi @dimqua ,
Thanks and I fully agree with the explanation. I think py-kms itself is not mature yet, especially for https://github.com/ThunderEX/py-kms/issues/6. I will try to tag for release when it's mature enough.
