### ISSUE TITLE
 INFORMATION IN GUI SERVER

### ISSUE THREAD

**Issue by FRED92G** [ThunderEX/py-kms#34]
HELLO WILL IT BE POSSIBLE THAT IN THE GUI OF THE SERVER IT TELLS US FOR WHICH PRODUCT IT TO ATTRIBUTE AN ACTIVATION
THANK YOU

**Comment by ThunderEX** [comment]
What do you mean by "WHICH PRODUCT IT TO ATTRIBUTE AN ACTIVATION"?

**Comment by FRED92G** [comment]
he should tell us which edition of windows and office to which he gives an activation for example windows
7 requests an activation the server mistletoe tells us ip thing has received an authorization for win 7 integral or pro

**Comment by ThunderEX** [comment]
It's already printed in the log, isn't it?

**Comment by FRED92G** [comment]
we find it or the newspaper

**Comment by FRED92G** [comment]
I have try as its and I have no file or log folder to create in the server folder
D: \ SOFTWARE \ py-kms-master \ server.py -o

**Comment by ThunderEX** [comment]
It's printing in the command line. Could you redirect cmd output to a file?

**Comment by FRED92G** [comment]
I am just looking for a solution to have the ip and the type of windows and office activate that its be precise you tell me in the log my the log I have try the option -o and nothing is created in the folder where is located kms i use kms on a windows 10 1909 could you check that the log function works and tell me how to make it work

**Comment by FRED92G** [comment]
I tried it like the log file and empty output
D: \ SOFTWARE \ py-kms-master> SERVER.PY> \ SOFTWARE \ py-kms-master \ LOG.TXT
